project:
  type: website

website:
  title: "KB's Visual Analytics "
  sidebar:
    logo: dataviz.jpeg
    style: "docked"
    background: dark
    search: true
    alignment: left
    collapse-level: 1
    contents:
      - text: 'Home'
        href: index.qmd
      - section: "Hands-on Exercises"
        contents:
          - text: 'Ex 1: A Layered Grammar of Graphics - ggplot2 methods'
            href: Hands-On_Ex/Hands-On_Ex01/Hands-on_Ex1.qmd
          - text: 'Ex 2: Beyond ggplot2 Fundamentals'
            href: Hands-On_Ex/Hands-On_Ex02/Hands-on_Ex2.qmd
          - text: 'Ex 3a: Programming Interactive Data Visualisations'
            href: Hands-On_Ex/Hands-On_Ex03/Hands-on_Ex3a.qmd
          - text: 'Ex 3b: Programming Animated Data Visualisations'
            href: Hands-On_Ex/Hands-On_Ex03/Hands-on_Ex3b.qmd
      - section: "In-class Exercises"
        contents:
          - text: 'Ex 1: A Light Makeover of ggplots'
            href: In-Class_Ex/In-Class_Ex01/In-Class_Ex1.qmd
          - text: 'Ex 3: TBC'
            href: In-Class_Ex/In-Class_Ex03/In-Class_Ex3.qmd
      - section: "Tableau"
        contents:
          - text: 'Superstore Annual Sales and Profit'
            href: Tableau/1_Superstore.qmd
          - text: 'The Superstore Story'
            href: Tableau/2_Superstore_Story.qmd
          - text: 'Animinated Bubbleplot and Cross-Filtering of Charts'
            href: Tableau/3_Animation_CrossFiltering.qmd
  page-navigation: true
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
          - text: 'Ex 1 A Layered Grammar of Graphics - ggplot2 methods'
            href: Hands-On_Ex/Hands-On_Ex01/Hands-on_Ex1.qmd
          - text: 'Ex 2 Beyond ggplot2 Fundamentals'
            href: Hands-On_Ex/Hands-On_Ex02/Hands-on_Ex2.qmd
          - text: 'Ex 3a: Programming Interactive Data Visualisations'
            href: Hands-On_Ex/Hands-On_Ex03/Hands-on_Ex3a.qmd
          - text: 'Ex 3b: Programming Animated Data Visualisations'
            href: Hands-On_Ex/Hands-On_Ex03/Hands-on_Ex3b.qmd
          
      - text: In-class Exercises
        menu: 
          - text: Ex 1 A Light Makeover of ggplots
            href: In-Class_Ex/In-Class_Ex01/In-Class_Ex1.qmd
          - text: 'Ex 3: TBC'
            href: In-Class_Ex/In-Class_Ex03/In-Class_Ex3.qmd
    right:
      - text: KB's GeoSpatial Analytics
        href: https://kaleidoscopic-bunny-isss624.netlify.app/
format:
  html:
    theme: flatly
    css: styles.css
    toc: true


editor: visual

