project:
  type: website

website:
  title: "KB's Visual Analytics "
  sidebar:
    logo: dataviz.jpeg
    style: "docked"
    background: dark
    search: true
    alignment: left
    collapse-level: 1
    contents:
      - text: 'Home'
        href: index.qmd
        
      - section: "In-class Exercises"
        contents:
          - text: '1 A Light Makeover of ggplots'
            href: In-Class_Ex/In-Class_Ex01/In-Class_Ex1.qmd
          - text: '2 Publishing a Quarto Document'
            href: In-Class_Ex/In-Class_Ex03/In-Class_Ex3.qmd
          - text: '3 Quantile–quantile plots'
            href: In-Class_Ex/In-Class_Ex04/In-Class_Ex4.qmd
          - text: '4 Working with json files for Network Analysis'
            href: In-Class_Ex/In-Class_Ex05/In-Class_Ex5.qmd
          - text: '5 Animinated Bubbleplot and Cross-Filtering of Charts'
            href: Tableau/3_Animation_CrossFiltering.qmd
          - text: '6 Plots for multi-variate analysis'
            href: Tableau/4_multivariate_plots.qmd
          - text: '7 Time Plots'
            href: Tableau/5_time_plots.qmd
          - text: '8 Visualise Geographic Data'
            href: Tableau/6_geospatial_plots.qmd
          - text: '9 Information Dashboard'
            href: Tableau/7_Information_Dashboard.qmd
            

      - section: "Take-home Exercises"
        contents:
          - text: '1.City of Engagement: Demographics and Financial Health of its Residents'
            href: Take-Home_Ex/Take-Home_Ex01/Take-Home_Ex1.qmd
          - text: '2.FishEye Knowldge Graph: Temporal Patterns of individual entities and between entities'
            href: Take-Home_Ex/Take-Home_Ex02/Take-Home_Ex2.qmd
          - text: '3.Countering illegal fishing: Identify anomalies in the business groups'
            href: Take-Home_Ex/Take-Home_Ex03/Take-Home_Ex3.qmd
                  

      - section: "Hands-on Exercises"
        contents:
          - text: '1 A Layered Grammar of Graphics - ggplot2 methods'
            href: Hands-On_Ex/Hands-On_Ex01/Hands-on_Ex1.qmd
          - text: '2 Beyond ggplot2 Fundamentals'
            href: Hands-On_Ex/Hands-On_Ex02/Hands-on_Ex2.qmd
          - text: '3 Programming Interactive Data Visualisations'
            href: Hands-On_Ex/Hands-On_Ex03/Hands-on_Ex3a.qmd
          - text: '4 Programming Animated Data Visualisations'
            href: Hands-On_Ex/Hands-On_Ex03/Hands-on_Ex3b.qmd
          - text: '5 Visual Statistical Analysis'
            href: Hands-On_Ex/Hands-On_Ex04/Hands-on_Ex4a.qmd
          - text: '6 Visualise Uncertainty'
            href: Hands-On_Ex/Hands-On_Ex04/Hands-on_Ex4b.qmd
          - text: '7 Funnel Plots for Fair Comparison'
            href: Hands-On_Ex/Hands-On_Ex04/Hands-on_Ex4c.qmd
          - text: '8 Visualise Distributions'
            href: Hands-On_Ex/Hands-On_Ex05/Hands-on_Ex5a.qmd
          - text: '9 Visualise Network Data'
            href: Hands-On_Ex/Hands-On_Ex05/Hands-on_Ex5b.qmd
          - text: '10 Ternary Plot to display composition of 3 variables'
            href: Hands-On_Ex/Hands-On_Ex06/Hands-on_Ex6a.qmd
          - text: '11 Visual Correlation Analysis of Numerical and Categorical Data'
            href: Hands-On_Ex/Hands-On_Ex06/Hands-on_Ex6b.qmd
          - text: '12 Heatmap to visualise Multivariate Data'
            href: Hands-On_Ex/Hands-On_Ex06/Hands-on_Ex6c.qmd
          - text: '13 Visual Multivariate Analysis with Parallel Coordinates Plot'
            href: Hands-On_Ex/Hands-On_Ex06/Hands-on_Ex6d.qmd
          - text: '14  Treemap Visualisation'
            href: Hands-On_Ex/Hands-On_Ex06/Hands-on_Ex6e.qmd
          - text: '15 Choropleth Mapping'
            href: Hands-On_Ex/Hands-On_Ex08/Hands-on_Ex8a.qmd
          - text: '16  Visualise Geospatial Point Data'
            href: Hands-On_Ex/Hands-On_Ex08/Hands-on_Ex8b.qmd
          - text: '17  Analytical Mapping on Choropleth'
            href: Hands-On_Ex/Hands-On_Ex08/Hands-On_Ex8c.qmd
          - text: '18  Information Dashboard Design'
            href: Hands-On_Ex/Hands-On_Ex09/Hands-On_Ex9.qmd
          - text: '19 Visualise And Analyse Time-Oriented Data'
            href: Hands-On_Ex/Hands-On_Ex07/Hands-On_Ex7a.qmd
          - text: '20  Time on the Horizon: ggHoriPlot methods'
            href: Hands-On_Ex/Hands-On_Ex07/Hands-On_Ex7b.qmd
          - text: '21 Extract and Visualise Financial Data Information'
            href: Hands-On_Ex/Hands-On_Ex10/Hands-On_Ex10.qmd
            
            
            
      - section: "Tableau"
        contents:
          - text: 'Superstore Annual Sales and Profit'
            href: Tableau/1_Superstore.qmd
          - text: 'The Superstore Story'
            href: Tableau/2_Superstore_Story.qmd

            
  page-navigation: true
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
          - text: '1 A Layered Grammar of Graphics - ggplot2 methods'
            href: Hands-On_Ex/Hands-On_Ex01/Hands-on_Ex1.qmd
          - text: '2 Beyond ggplot2 Fundamentals'
            href: Hands-On_Ex/Hands-On_Ex02/Hands-on_Ex2.qmd
          - text: '3 Programming Interactive Data Visualisations'
            href: Hands-On_Ex/Hands-On_Ex03/Hands-on_Ex3a.qmd
          - text: '4 Programming Animated Data Visualisations'
            href: Hands-On_Ex/Hands-On_Ex03/Hands-on_Ex3b.qmd
          - text: '5 Visual Statistical Analysis'
            href: Hands-On_Ex/Hands-On_Ex04/Hands-on_Ex4a.qmd
          - text: '6 Visualise Uncertainty'
            href: Hands-On_Ex/Hands-On_Ex04/Hands-on_Ex4b.qmd
          - text: '7 Funnel Plots for Fair Comparison'
            href: Hands-On_Ex/Hands-On_Ex04/Hands-on_Ex4c.qmd
          - text: '8 Visualise Distributions'
            href: Hands-On_Ex/Hands-On_Ex05/Hands-on_Ex5a.qmd
          - text: '9 Visualise Network Data'
            href: Hands-On_Ex/Hands-On_Ex05/Hands-on_Ex5b.qmd
          - text: '10 Ternary Plot to display composition of 3 variables'
            href: Hands-On_Ex/Hands-On_Ex06/Hands-on_Ex6a.qmd
          - text: '11 Visual Correlation Analysis of Numerical and Categorical Data'
            href: Hands-On_Ex/Hands-On_Ex06/Hands-on_Ex6b.qmd
          - text: '12 Heatmap to visualise Multivariate Data'
            href: Hands-On_Ex/Hands-On_Ex06/Hands-on_Ex6c.qmd
          - text: '13 Visual Multivariate Analysis with Parallel Coordinates Plot'
            href: Hands-On_Ex/Hands-On_Ex06/Hands-on_Ex6d.qmd
          - text: '14  Treemap Visualisation'
            href: Hands-On_Ex/Hands-On_Ex06/Hands-on_Ex6e.qmd
          - text: '15 Choropleth Mapping'
            href: Hands-On_Ex/Hands-On_Ex08/Hands-on_Ex8a.qmd
          - text: '16  Visualise Geospatial Point Data'
            href: Hands-On_Ex/Hands-On_Ex08/Hands-on_Ex8b.qmd
          - text: '17  Analytical Mapping on Choropleth'
            href: Hands-On_Ex/Hands-On_Ex08/Hands-on_Ex8c.qmd
          - text: '18  Information Dashboard Design'
            href: Hands-On_Ex/Hands-On_Ex09/Hands-On_Ex9.qmd
          - text: '19 Visualise And Analyse Time-Oriented Data'
            href: Hands-On_Ex/Hands-On_Ex07/Hands-On_Ex7a.qmd
          - text: '20  Time on the Horizon: ggHoriPlot methods'
            href: Hands-On_Ex/Hands-On_Ex07/Hands-On_Ex7b.qmd
          - text: '21 Extract and Visualise Financial Data Information'
            href: Hands-On_Ex/Hands-On_Ex10/Hands-On_Ex10.qmd
            
      - text: In-class Exercises
        menu: 
          - text: '1 A Light Makeover of ggplots'
            href: In-Class_Ex/In-Class_Ex01/In-Class_Ex1.qmd
          - text: '2 Publishing a Quarto Document'
            href: In-Class_Ex/In-Class_Ex03/In-Class_Ex3.qmd
          - text: '3 Quantile–quantile plots'
            href: In-Class_Ex/In-Class_Ex04/In-Class_Ex4.qmd
          - text: '4 Working with json files for Network Analysis'
            href: In-Class_Ex/In-Class_Ex05/In-Class_Ex5.qmd
          - text: '5 Animinated Bubbleplot and Cross-Filtering of Charts'
            href: Tableau/3_Animation_CrossFiltering.qmd
          - text: '6 Plots for multi-variate analysis'
            href: Tableau/4_multivariate_plots.qmd
          - text: '7 Time Plots'
            href: Tableau/5_time_plots.qmd
          - text: '8 Visualise Geographic Data'
            href: Tableau/6_geospatial_plots.qmd
          - text: '9 Information Dashboard'
            href: Tableau/7_Information_Dashboard.qmd
            
      - text: Take-home Exercises
        menu:
          - text: '1.City of Engagement: Demographics and Financial Health of its Residents'
            href: Take-Home_Ex/Take-Home_Ex01/Take-Home_Ex1.qmd
          - text: '2.FishEye Knowldge Graph: Temporal Patterns of individual entities and between entities'
            href: Take-Home_Ex/Take-Home_Ex02/Take-Home_Ex2.qmd
          - text: '3.Countering illegal fishing: Identify anomalies in the business groups'
            href: Take-Home_Ex/Take-Home_Ex03/Take-Home_Ex3.qmd
            
      - text: Project Hooked
        href: https://vaa-groupfour.netlify.app/
          
            
    right:
      - text: KB's GeoSpatial Analytics
        href: https://kaleidoscopic-bunny-isss624.netlify.app/
format:
  html:
    theme: flatly
    css: styles.css
    toc: true


editor: visual

