[build]
  command = "wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.4.553/quarto-1.4.553-linux-amd64.deb && sudo dpkg -i quarto-1.4.553-linux-amd64.deb && quarto render"
  publish = "_site"
